apiVersion: apps/v1
kind: Deployment
metadata:
  name: advance-trading-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: advance-trading-backend
  template:
    metadata:
      labels:
        app: advance-trading-backend
    spec:
      containers:
      - name: backend
        image: advance-trading-backend:latest
        ports:
        - containerPort: 5000
