apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: advance-trading

resources:
- namespace.yaml
- configmap.yaml
- secret.yaml
- deployment-db.yaml
- deployment-backend.yaml
- deployment-frontend.yaml
- service-db.yaml
- service-backend.yaml
- service-frontend.yaml
- pvc-db.yaml
- ingress.yaml
- db-init-configmap.yaml
