apiVersion: v1
kind: Secret
metadata:
  name: advance-secrets
  namespace: advance-trading
type: Opaque
stringData:
  SMTP_USER: karenramiresjudith@gmail.com
  SMTP_PASS: zxmeytebkfwlwywx
  ENCRYPTION_KEY: f748f96f21794701c110a9d30ff4b68bafdacd47ebe9c4eede8a7492bb960180
  MERCADOPAGO_ACCESS_TOKEN: "TEST-123"
  MERCADOPAGO_PUBLIC_KEY: "TEST-456"
  DB_PASSWORD: postgres
