apiVersion: v1
kind: Service
metadata:
  name: advance-trading-backend
spec:
  selector:
    app: advance-trading-backend
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
  type: LoadBalancer
